[package]
name = "gqlforum-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "gqlforum"

[dependencies]
axum = "0.5"
tokio = { version = "1", features = ["full"] }

async-graphql = "4"
async-graphql-axum = "4"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.sqlx]
version = "0.6"
features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlite",
    "uuid",
    "json",
    "time",
    "migrate",
    "offline",
]